import { test, expect } from '@playwright/test';

test('Login Test Auto Generated By Pw', async ({ page }) => {

    await page.goto("https://login.salesforce.com/");

    await page.locator("//*[@id='username']").fill("RCV");
    await page.locator("#password").fill("RCV");
    await page.locator("//input[@id='Login']").click();
    
    await page.waitForTimeout(2000);
    await page.close();

});